title: Neelesh Reddi Data Science Portfolio
description: DTSC 2301 projects, reflections, and data analysis
theme: jekyll-theme-minimal
show_downloads: false

author: Neelesh Reddi
url: "https://nreddi2.github.io"
baseurl: "/data-science-portfolio"

github:
  is_project_page: false
